version: "3.7"

services:
  db:
    container_name: snippetbox 
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_DB: snippetbox 
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin   
    restart: always
    ports:
      - 5013:80
    environment:
      - PMA_ARBITRARY=1